### PR TITLE
Readd unused key

### PR DESCRIPTION
**Pull request by lk16**
This addresses #39

### CODE REVIEW

**Comment by lk16** [comment]
This PR depends on #35, so please review after this one is merged.

**Comment by sashimi-houdini** [comment]
Could you rebase on master? That would make reviewing easier.

**Comment by lk16** [comment]
> Could you rebase on master?

Done.

**Comment by atramos** [comment]
Two questions
- How does this work when the miner crashes?
- Could we read the blockchain for already used keys, instead of relying on the wallet annotation?

**Comment by lk16** [comment]
> How does this work when the miner crashes?
If the MinerWatcher process crashes without hitting the `finally` block (due to OOM or similar), the behaviour is the same as what we have on master right now.

Could we read the blockchain for already used keys, instead of relying on the wallet annotation?
In theory: yes, probably. But this won't scale well as the chain gets longer.

Scanning the entire chain for used keys sounds like a bad plan, especially since we should get away from loading the entire chain on boot.

**Comment by lk16** [comment]
I forgot to add reviewers here.

**Review by atramos — APPROVED** [review]

**Pull request merged**
