### PR TITLE
sqlite3 block store, remove pickle -- Fixes #109, #122

### LINKED ISSUE #93: delete code that still reads individual file blocks
In `utils.py` there is a comment that says `the code below is no longer needed by normal users, but some old testcases still rely on it`.

As a result of PR #90 the application no longer writes these files.

The old testcases should be updated and the code should be deleted.

### LINKED ISSUE #109: MemoryError in disk_interface.py:81 - pickle.dump(data, file)
`skepticoin-mine` occasionally crashes with the following error when running on a machine with 4GB of RAM. Earlier I was getting the error on a 2GB machine, and upgrading the memory allowed it to keep it going a few more weeks.

```
Traceback (most recent call last):
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev124+g9dbb2bd-py3.8.egg/skepticoin/networking/local_peer.py", line 86, in handle_remote_peer_selector_event
    remote_peer.handle_receive_data(recv_data)
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev124+g9dbb2bd-py3.8.egg/skepticoin/networking/remote_peer.py", line 305, in handle_receive_data
    self.receiver.receive(data)
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev124+g9dbb2bd-py3.8.egg/skepticoin/networking/remote_peer.py", line 109, in receive
    self.handle_message_data(self.buffer[:self.len])
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev124+g9dbb2bd-py3.8.egg/skepticoin/networking/remote_peer.py", line 120, in handle_message_data
    self.peer.handle_message_received(header, message)
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev124+g9dbb2bd-py3.8.egg/skepticoin/networking/remote_peer.py", line 279, in handle_message_received
    return self.handle_data_message_received(header, message)
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev124+g9dbb2bd-py3.8.egg/skepticoin/networking/remote_peer.py", line 438, in handle_data_message_received
    return self.handle_block_received(header, message)
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev124+g9dbb2bd-py3.8.egg/skepticoin/networking/remote_peer.py", line 486, in handle_block_received
    self.local_peer.disk_interface.write_chain_cache_to_disk(coinstate_changed)
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev124+g9dbb2bd-py3.8.egg/skepticoin/networking/disk_interface.py", line 81, in write_chain_cache_to_disk
    coinstate.dump(lambda data: pickle.dump(data, file))
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev124+g9dbb2bd-py3.8.egg/skepticoin/coinstate.py", line 132, in dump
    dumper(self.block_by_hash)
  File "/home/ec2-user/venv/lib64/python3.8/site-packages/skepticoin-0.1.15.dev124+g9dbb2bd-py3.8.egg/skepticoin/networking/disk_interface.py", line 81, in <lambda>
    coinstate.dump(lambda data: pickle.dump(data, file))
```

A quick search through Google and Stackoverflow indicates excessive memory usage is a common problem with `pickle`, and one common solution is to replace `pickle` with `cPickle`.

Reference:
https://stackoverflow.com/questions/17513036/pickle-dump-huge-file-without-memory-error

As a workaround, add memory to mining machine.

### LINKED ISSUE #119: network instability issues (updated)
These are fun times to be mining Skepticoin.

A few things I noticed:

- Only one peer remains up (not mine)
- My own nodes I try to run keep crashing, or they are running but don't appear on the list of peers when I try to add a 3rd or 4th machine.
- The one peer which is not mine behaves erratically, my logs showing Connection refused, Connection reset, No route to host.
- My node keeps retransmitting the entire blockchain to the one peer, over and over.
- Multiple "microforks" (blockchain diverges by few blocks) logged by the peers that manage to stay up a while.
- Additional instances of the one peer showing up on different TCP/IP Ports (non-2412) causing "No route to host" on my end
- Peers not responding to GetBlocksMessages or GetBlocksMessages not being sent. 
- Initially noticed GetBlocksMessages are sent twice to the same peer, after fixing this I noticed the peer disconnects in response to a legit 2nd GetBlocksMessages
- `netstat -an` showing "Recv-Q" backlog indicating the code is not reading the data from the sockets

### LINKED ISSUE #122: forks!
The blockchain keeps forking, way more than it used to.

In the logs, this shows up as `Diverges at N blocks`

### PR DESCRIPTION
**Pull request by refacktor**
Sqlite3-based blockstore solution. This has been tested and re-written a couple of times.

- Replaces pickle which was causing #109 
- Speeds up chain writes, which fixes #122 
- This change also provides a solid foundation for future work on #80 
- Also fixes #93 
- Mostly fixes #119 except for a few lingering items noted in the last comment

### CODE REVIEW

**Comment by sashimi-houdini** [comment]
I'm going to merge this in the belief that it's definitely the right direction to go into; I didn't do a thorough check of the code (yet) but we can always revisit this PR later as long as a new version hasn't been released yet.

**Comment by sashimi-houdini** [comment]
This PR seems to introduce some hickup while mining. On my local machine:

```
2022-xx-xx xx:x4:40 | uptime: 0:32:26 |  32 hash/sec | mined:  60 SKEPTI | xxxxxx SKEPTI/h |   x peers | h. 3xxxx6 @ 17s ago
miner 0 found block: 003457xx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2022-xx-xx xx:x4:41 | uptime: 0:32:27 |  29 hash/sec | mined:  70 SKEPTI | xxxxxx SKEPTI/h |   x peers | h. 3xxxx7 @ 0s ago
2022-xx-xx xx:x5:04 | uptime: 0:32:50 |  29 hash/sec | mined:  70 SKEPTI | xxxxxx SKEPTI/h |   x peers | h. 3xxxx7 @ 23s ago
```
This is right after the merge. A node running Skepticoin 3.0 doesn't have such hickups. I did not investigate further.

**Comment by refacktor** [comment]
Where is the hiccup? This output looks normal.

**Comment by refacktor** [comment]
@sashimi-houdini I'm still puzzled by our last comment. Your log shows:

-  at xx:x4:40 the chain height was 3xxxx6 and the chain head was 17 seconds old
-  you mined the block at height 003457x7
- at xx:x4:41 the chain height was 3xxxx7 and the chain head was 0 seconds old (yep, you just mined it!)
- at xx:x5:04 the chain height was still 3xxxx7 and the chain head was 23 seconds old (the time math checks out!)

**Comment by sashimi-houdini** [comment]
The math for chain heights and clock times checks out. The problem is that 23 seconds passed on the clock, and no new lines were added to my terminal in the meantime. Not sure if no mining took place in that timeframe, didn't examine that yet.

**Comment by refacktor** [comment]
@sashimi-houdini  Are you using the `--quiet` CLI option? The behavior you describe is consistent with `--quiet`: The output is suppressed if nothing happened. The relatively new code that does this is in [mining.py:171](https://github.com/skepticoin/skepticoin/blob/master/skepticoin/mining.py#L171)

If you are not using `--quiet` then this apparently a bug.

**Pull request merged**
