### PR TITLE
Fix configure_logging_from_args

### PR DESCRIPTION
**Pull request by marekjedrzejewski**
needed hasattr instead of args.name

### CODE REVIEW

**Review by hunter-bidens-laptop — APPROVED** [review]

**Comment by marekjedrzejewski** [comment]
After second thought it might also need and args.name after hasattr, because hasattr prevents it from crashing, when there's no arguments, but if arguments are parsed and are actually representing anything instead of just being in args class, it might also need to read them.

**Comment by hunter-bidens-laptop** [comment]
Wanted to confirm that this exact error exists in newest Ubuntu run from inside of a VM. What's the best way to run this code and on which environment?

**Comment by sashimi-houdini** [comment]
@hunter-bidens-laptop I've been looking for you (but not very hard).

>  What's the best way to run this code and on which environment?

Whatever works, I haven't committed to any kind of platform support yet, but the more the better, so I'm happy to take PRs like this one.

I'm personally running on Python 3.8 on a somewhat recent Linux, but I know of people who got this to work on plain Windows (no WSL) as well as on MacOS (presumably working around the fact that MacOS comes with Python 2).

**Comment by sashimi-houdini** [comment]
@hunter-bidens-laptop @marekjedrzejewski what version of Python are you on? I'd rather have full understanding before merging

**Comment by hunter-bidens-laptop** [comment]
> @hunter-bidens-laptop @marekjedrzejewski what version of Python are you on? I'd rather have full understanding before merging

Python 3.8.5 running on Ubuntu (5.8.0-50-generic)

**Comment by marekjedrzejewski** [comment]
```
Python 3.9.4 (default, Apr 20 2021, 15:51:38) 
[GCC 10.2.0] on linux
```

**Comment by sashimi-houdini** [comment]
Thanks @hunter-bidens-laptop that screenshot rubber-ducked me to the source of the problem. (You know: actually running the command `skepticoin-receive`, which was apparently broken for everyone). Fixed in `0.1.11`.

**Pull request closed without merging**
