### PR TITLE
Cloud Mining Extension

### PR DESCRIPTION
**Pull request by atramos**
This PR contains a complete solution for mining skepticoin on AWS. It has dependencies on other open PRs.

### CODE REVIEW

**Comment by lk16** [comment]
Some thoughts:
* I think this should be in a separate repository. 
* What is `169.254.169.254`? This IP is hardcoded in one of your yaml files
* I don't see any instructions on how to use this. Can you add a README?

**Comment by atramos** [comment]
This PR is very small if all the other open PRs are approved first.
The 169.254.169.254 is the AWS Metadata Service. It's not a real IP.
I added a README.

**Comment by sashimi-houdini** [comment]
I'll look at this more seriously once the other open PRs are approved first, and the smallness of this PR becomes more obvious. However, my first feeling is indeed that this should be in a separate repository. If that feeling sticks, I'd still be happy to grant an air of approvedness by creating a repo for you in the skepticoin github organization.

**Comment by atramos** [comment]
> * What is `169.254.169.254`? This IP is hardcoded in one of your yaml files

It turns out this wasn't even necessary. Removed it in bec2e5cdf5b597749443c7a97340b9ed24393abe.

**Comment by sashimi-houdini** [comment]
> once the other open PRs are approved first

I guess it also needs to be rebased on master to make the simplicity visible

**Comment by atramos** [comment]
This PR has been rebased! It's now just a README file and 3 yaml files. Based on discussions above, I also started calling it an "Extension", and moved it into an "extensions" folder outside of the skepticoin root. This should be a reasonable compromise between potentially having the cloud stuff confused for "core" skepticoin, which it is not, vs making a separate repo, which is overkill. Hopefully this also sets the pattern for future Extensions.

**Comment by lk16** [comment]
I'll just go ahead and merge this. If we want to go another route later, that would be easy, since it's just 3 text files in a separate folder.

**Pull request merged**
