### PR TITLE
fix #99: error writing mined block to disk

### LINKED ISSUE #99: Crash when mining after deleting chain folder
I deleted my chain folder and the miner ran into this errror

```Traceback (most recent call last):
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/mining.py", line 142, in __call__
    self.handle_received_message(queue_item)
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/mining.py", line 196, in handle_received_message
    handler(miner_id, data)
  File "/home/luuk/projects/skepticoin-mining/venv/lib/python3.8/site-packages/skepticoin/mining.py", line 245, in handle_scrypt_output_message
    with open(Path('chain') / block_filename(block), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'chain/00102316-00005b08fe2de19be185db3459b27cf293366f3b186927e60d1f51513e8314d9'
```

I didn't look into it, but looks like my miner crashed after mining a block.

### PR DESCRIPTION
**Pull request by atramos**
This PR fixes Issue #99.

### CODE REVIEW

**Comment by atramos** [comment]
@lk16 this fix has been tested and rebased, and ready for review. There was an interesting complication which I found during testing. The mining thread and the networking thread were conflicting by simultaneously calling `write_chain_cache_to_disk`. So I removed the write from the mining thread. This seems to work well based on my testing.

**Comment by atramos** [comment]
#101

**Comment by atramos** [comment]
@lk16 I think we should emergency release this. It impacts new users.

**Review by lk16 — APPROVED** [review]

**Comment by lk16** [comment]
Sure, let's push out another release.

**Pull request merged**
