### PR TITLE
Let Miner do little more than scrypt

### PR DESCRIPTION
**Pull request by lk16**
In this PR I want to:
* Have one NetworkingThread: in MinerWatcher
* Load the chain once: in MinerWatcher
* Handle the wallet once: in ... you guessed it

Effectively, Miner should be stripped to:
* calling scrypt
* facilitating the call to scrypt (including dealing with its return value)
* any other bookkeeping that cannot be done in MinerWatcher

At time of posting, this PR is ahead of my branches in #16 and #26, so those should be merged before this PR.
Furthermore, the implementation is not done yet.

### CODE REVIEW

**Comment by lk16** [comment]
I seem to have fixed a bug that caused MinerWatcher to crash with a KeyError, due to using an outdated CoinState. 
It used to crash within seconds and is currently running for a few minutes on my machine without any trouble.
I think this is the right time to get some reviews for this PR. @atramos @sashimi-houdini

**Comment by lk16** [comment]
@atramos please check this one

**Comment by atramos** [comment]
> @atramos please check this one

I'm looking into it, I think it conflicts with --quiet and multi-mining.

**Comment by atramos** [comment]
Not sure if this is working...
```
miner  0: Starting mining: A repeat minter
Stopping networking thread
Waiting for networking thread to stop
```

**Comment by atramos** [comment]
@lk16 please see if you can cherry-pick 7948de7a4b5d8e833e265abc3b8b09a387077b9a and db2797049ea76139863f5918c51ff96019169b68. I tried pushing a PR into your branch but I'm not sure if that's going to work very well either.

**Comment by lk16** [comment]
I rebased this over the new master.

**Pull request merged**
