### PR TITLE
fix issues that were causing forks, crashes, and slowness

### PR DESCRIPTION
**Pull request by refacktor**
Multiple fixes to try to stop my nodes from crashing, see #119

### CODE REVIEW

**Comment by atramos** [comment]
@sashimi-houdini this is ready for production... I recommend releasing ASAP along with #113 & #123 to stabilize the network and allow new nodes to join in.

**Comment by atramos** [comment]
@sashimi-houdini This is really final now... I've started work on a new PR.

**Comment by atramos** [comment]
This PR has become obsolete due to other changes I've started working on. I'm flipping this back to Draft to minimize change history churn and avoid double-review in some areas.

**Comment by refacktor** [comment]
this has now been broken up into smaller PRs

**Pull request closed without merging**
