### PR TITLE
fix for pop from empty list

### PR DESCRIPTION
**Pull request by csheldrick**
Fix pop from empty list when wallet runs out of unused public keys

### CODE REVIEW

**Review by atramos — CHANGES_REQUESTED** [review]
This is not a good fix for people running multiple nodes.

**Comment by csheldrick** [comment]
Generate another 10,000 instead? Somewhere else instead of here?

**Comment by atramos** [comment]
From my perspective (a bit selfish based on how I'm running my nodes) I'd prefer to just re-use keys, or provide an easy way to create a much bigger wallet from the original wallet, but not on the fly -- it needs to be an explicit administrative operation so that I can distribute the bigger wallet to all the nodes.

**Comment by lk16** [comment]
> provide an easy way to create a much bigger wallet from the original wallet, but not on the fly

I like this, maybe a new command would be a nice solution? Something like `skepticoin-wallet` which takes some flags or sub commands as commandline parameters?

**Comment by csheldrick** [comment]
Are you guys seeing any peers on your nodes?

**Comment by atramos** [comment]
Closing in favor of PR #113

**Comment by sashimi-houdini** [comment]
Thanks to the participants in this issue for helping us complete the following milestone

[x] bunch of early accidentally doxx themselves and reveal that they currently own more than 0.5% of the global eternal supply of skepticoin

**Pull request closed without merging**
