### PR TITLE
Update mine.py

### PR DESCRIPTION
**Pull request by mplantsheer**
I would like to have an easy way to see the time spend, this would do

### CODE REVIEW

**Comment by lk16** [comment]
This would just show the current time every second, not the time spent.

I was thinking about printing several stats per second, but keeping all of them on one line.

Something like:
```
2021-05-09 14:01:05 | uptime:   2 days, 13:27:04 |  14 h/sec | mined 3130 SKE | 21.37 SKE/hour
2021-05-09 14:01:06 | uptime:   2 days, 13:27:05 |  13 h/sec | mined 3130 SKE | 21.37 SKE/hour
...
```

**Comment by mplantsheer** [comment]
Yes that be even better but I was lazy and this would do for me :) I just wanted to get a sense of how long it has been since last block was found by me

**Comment by lk16** [comment]
I made PR #17 to add printing some stats while mining. It doesn't show how long the last block ago was, but I think the average block speed or SKE per hour should do.

**Comment by sashimi-houdini** [comment]
Let's take the discussion over to #17 and close this one.

**Pull request closed without merging**
